image: python:3.9

stages:
  - lint
  - test

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

black:
  stage: lint
  script:
    - poetry run black --diff --check .

mypy:
  stage: lint
  script:
    - poetry run mypy .

isort:
  stage: lint
  script:
    - poetry run isort --diff --check .

pytest:
  stage: test
  script:
    - poetry run pytest -v --cov=ansible_docs
    - poetry run coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
